language: php

php:
  #- 5.4
  #- 5.5
  - 5.6

env:
  global:
    - PLUGIN_NAME=StatelessAuth
    - REQUIRE=""

  matrix:
    - DB=mysql CAKE_VERSION=2.6

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
	- COVERALLS=1
    - php: 5.6
      env:
	- PHPCS=1

before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
