language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - PLUGIN_NAME=StatelessAuth
  matrix:
    - DB=mysql CAKE_VERSION=2.6

matrix:
  fast_finish: true

before_install:
  - composer self-update

install:
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - cp -R ../CakePHP-Stateless-Auth plugins/StatelessAuth
  - chmod -R 777 ../cakephp/app/tmp
  - sh -c "composer global require 'phpunit/phpunit=3.7.33'"
  - sh -c "ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit ../cakephp/vendors/PHPUnit"

before_script:
  - ./build/travis_before_script.sh

script:
  - ./build/travis_script.sh

# After a Successful Build
after_success:
  - ./build/travis_after_success.sh

# After a Failed Build
after_failure:

# After every Build
after_script:

# Notifications Settings
notifications:
  email: false
